FROM mysql

ENV MYSQL_USER=tester001
ENV MYSQL_PASSWORD=tester001
ENV MYSQL_ROOT_PASSWORD=dotdot00!
ENV MYSQL_DATABASE=testerdb

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]