version: '3'
services:
  db:  # 동일한 키워드(db)로 설정해야함.
    build:
      context: ./docker-test-db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./docker-test-db/store:/var/lib/mariadb
    networks:
      - network
  server:
    build:
      context: ./docker-test-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db  # db가 준비되면 실행됨.
    environment: # application.yml에 사용될 환경변수 설정.
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/ssardb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_DRIVER: org.mariadb.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    networks:
      - network

networks:
  network: # 동일한 키워드(network)로 설정해야함.