server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    # docker-compose.yml 환경 변수 설정
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: ${SPRING_DATASOURCE_DRIVER}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/metadb?serverTimezone=Asia/Seoul
#    username: root
#    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true

logging:
  level:
    "[com.example.server]": INFO
    "[org.hibernate.type]": TRACE
