services:
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dotdot00!
      - MYSQL_DATABASE=rootdb
#    ports:
#      - "3306:3306"

volumes:
  mysql-compose-volume: